### ISSUE TITLE
Theme broken on Gnome 46

### ISSUE THREAD

**Issue by Emiliasky** [catppuccin/gtk#161]
**Describe the bug**
Notifications take up the entire width of the screen.

**Mention your distribution and your theme version**
Arch linux
Theme version: 0.7.1-1

**Select how you installed the theme**
- [ ] GitHub Releases
- [x] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Yes

**Expected behavior**
Notifications render like they do in gnome 45: not taking up the entire width of the screen.

**Screenshots**
Theme disabled:
![Screenshot from 2024-03-24 12-47-35](https://github.com/catppuccin/gtk/assets/48217459/e82c2683-7e7d-4552-8209-c9d2ef146206)

Theme enabled:
![Screenshot from 2024-03-24 12-43-55](https://github.com/catppuccin/gtk/assets/48217459/63335e83-fc08-4705-9943-f70756f840d2)

**Additional context**
I just updated to gnome 46 today. The theme worked fine on gnome 45.

**Comment by khaitranhq** [comment]
same issue

**Comment by ken-kuro** [comment]
Seem like it's from the base theme: https://github.com/vinceliuice/Colloid-gtk-theme/issues/146

**Comment by clys-man** [comment]
same issue

**Comment by cucumber-sp** [comment]
same issue

**Comment by cucumber-sp** [comment]
> Seem like it's from the base theme: [vinceliuice/Colloid-gtk-theme#146](https://github.com/vinceliuice/Colloid-gtk-theme/issues/146)

works, but notif menu is still broken
![image](https://github.com/catppuccin/gtk/assets/100789522/bdf73dff-847d-4cde-95d5-c028322b0897)

**Comment by AderynCrow** [comment]
the fix in https://github.com/vinceliuice/Colloid-gtk-theme/pull/147/commits/1a1918e4c36ff46c2ddf9292031fd19f68dff271 works, i've manually changed it for me, however i don't really understand the generation process of this here theme so i can't apply it. is this just a kind of patcher for Colloid?

**Comment by nagendraallam** [comment]
.message-list { width: 31.5em; padding: 9px 0; border-width: 0; }

.message-list .message-list-placeholder StIcon { width: 0; height: 0; }

.message-list .message-list-placeholder StLabel { color: rgba(17, 21, 33, 0.55); font-weight: normal; font-size: 11pt; }

.message-list StScrollBar { padding: 2px 0; }

.message-list-sections { spacing: 12px; margin: 0 18px; }

.message-list-sections:ltr { margin-right: 9px; }

.message-list-sections:rtl { margin-left: 9px; }

.message-list-section, .message-list-section-list { spacing: 5px; }

.message-list-controls { font-weight: normal; margin: 18px 18px 0; padding: 0; spacing: 10px; }

.message-list-controls:ltr { margin-right: 9px; }

.message-list-controls:rtl { margin-left: 9px; }

.message-list-controls .dnd-button { border-width: 1px; border-color: transparent; border-radius: 99px; border-style: solid; }

.message-list-controls .dnd-button:focus { border-color: #5294e2; }

.message-list-clear-button { margin: 0; padding: 4px 12px; }

.message { margin: 0; text-shadow: none; padding: 3px; color: #111521; background-color: #FCFDFD; border: 1px solid #cfd6e6; border-radius: 2px; box-shadow: inset 4px 0 0 -1px #5294e2; text-shadow: none; }

.message:hover, .message:focus { color: #111521; border-color: #5294e2; }

.message:active { color: #ffffff; background-color: #5294e2; }

.message .message-icon-bin:ltr { padding: 8px 2px 8px 8px; }

.message .message-icon-bin:rtl { padding: 8px 8px 8px 2px; }

.message .message-icon-bin > StIcon { color: inherit; icon-size: 16px; -st-icon-style: symbolic; margin-top: 0.035em; }

.message .message-icon-bin > .fallback-app-icon { width: 16px; height: 16px; }

.message .message-content { padding: 8px; spacing: 0; margin: 0; }

.message .message-title { font-weight: bold; padding: 0; }

.message .message-secondary-bin { padding: 0 10px; }

.message .message-secondary-bin > .event-time { color: rgba(17, 21, 33, 0.6); font-size: 10pt; /* HACK: the label should be baseline-aligned with a 1em label, fake this with some bottom padding */ padding-bottom: 0.04em; }

.message .message-secondary-bin > .event-time:ltr { text-align: right; }

.message .message-secondary-bin > .event-time:rtl { text-align: left; }

.message:active .message-secondary-bin, .message:active .message-secondary-bin > .event-time { color: rgba(255, 255, 255, 0.6); }

.message .message-close-button { color: #111521; background-color: transparent; padding: 0; margin: 0; }

.message .message-close-button:hover { color: rgba(17, 21, 33, 0.7); }

.message .message-close-button:active { color: #5294e2; }

.message .message-close-button StIcon { icon-size: 16px; }

.message .message-body { color: inherit; }

.url-highlighter { link-color: #2679db; }

/* Media Controls */
.message-media-control { padding: 12px; margin: 0; color: #111521; background-color: transparent; }

.message-media-control:hover { color: rgba(17, 21, 33, 0.7); }

.message-media-control:active { color: #5294e2; }

.message-media-control:insensitive { color: rgba(17, 21, 33, 0.55); }

.message-media-control:last-child:ltr { padding-right: 18px; }

.message-media-control:last-child:rtl { padding-left: 18px; }

.message-media-control StIcon { icon-size: 16px; }

.message:active .message-media-control { color: #ffffff; }

.media-message-cover-icon { icon-size: 48px !important; }

.media-message-cover-icon.fallback { color: rgba(17, 21, 33, 0.55) !important; background-color: #F5F6F7; border-radius: 2px; icon-size: 32px !important; padding: 6px; border: 1px solid #dcdfe3; }

.message:active .media-message-cover-icon.fallback { color: rgba(255, 255, 255, 0.8) !important; background-color: #71a7e7; border-color: rgba(255, 255, 255, 0.8); }

![image](https://github.com/catppuccin/gtk/assets/39880569/4788ed36-d044-4b1a-b59f-d17bf3f4f6d5)

copied over css from a different theme and it seems to work well. didn't check what's exactly broken , but you can paste this for a quick fix

**Comment by rubyowo** [comment]
thanks for informing that colloid fixed it upstream! we'll update the colloid submodule.

**Comment by DarioZar** [comment]
> > Seem like it's from the base theme: [vinceliuice/Colloid-gtk-theme#146](https://github.com/vinceliuice/Colloid-gtk-theme/issues/146)
> 
> works, but notif menu is still broken ![image](https://private-user-images.githubusercontent.com/100789522/317782717-bdf73dff-847d-4cde-95d5-c028322b0897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjkzODgsIm5iZiI6MTcxMTk2OTA4OCwicGF0aCI6Ii8xMDA3ODk1MjIvMzE3NzgyNzE3LWJkZjczZGZmLTg0N2QtNGNkZS05NWQ1LWMwMjgzMjJiMDg5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMDU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDVlYjg5NmRiZTEyYmYwNWViMWQwNWQ3MTRiYTE4Y2RkMDc4Yzk0YjYwODBjZDZhZjEyMDJlZWMxNDVmODhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r_QkIPavwDnK09Czh2n3-pgkwnezkGoUdqjd0GupKb4)

I fixed this thing some days ago, so I created a PR for Colloid https://github.com/vinceliuice/Colloid-gtk-theme/pull/148, the commit is https://github.com/vinceliuice/Colloid-gtk-theme/pull/148/commits/714adbfbe4f65969e8d3fa5970bd4c2cfad94648
![immagine](https://github.com/catppuccin/gtk/assets/15327563/64342f48-9c2a-491f-b08d-656e763b3fda)

**Comment by Yt4aZaveta** [comment]
> > > Seem like it's from the base theme: [vinceliuice/Colloid-gtk-theme#146](https://github.com/vinceliuice/Colloid-gtk-theme/issues/146)
> > 
> > 
> > works, but notif menu is still broken jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjkzODgsIm5iZiI6MTcxMTk2OTA4OCwicGF0aCI6Ii8xMDA3ODk1MjIvMzE3NzgyNzE3LWJkZjczZGZmLTg0N2QtNGNkZS05NWQ1LWMwMjgzMjJiMDg5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMDU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDVlYjg5NmRiZTEyYmYwNWViMWQwNWQ3MTRiYTE4Y2RkMDc4Yzk0YjYwODBjZDZhZjEyMDJlZWMxNDVmODhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r_QkIPavwDnK09Czh2n3-pgkwnezkGoUdqjd0GupKb4)
> 
> I fixed this thing some days ago, so I created a PR for Colloid [vinceliuice/Colloid-gtk-theme#148](https://github.com/vinceliuice/Colloid-gtk-theme/pull/148), the commit is [vinceliuice/Colloid-gtk-theme@714adbf](https://github.com/vinceliuice/Colloid-gtk-theme/commit/714adbfbe4f65969e8d3fa5970bd4c2cfad94648) ![immagine](https://private-user-images.githubusercontent.com/15327563/318416046-64342f48-9c2a-491f-b08d-656e763b3fda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzI3MTUsIm5iZiI6MTcxMTk3MjQxNSwicGF0aCI6Ii8xNTMyNzU2My8zMTg0MTYwNDYtNjQzNDJmNDgtOWMyYS00OTFmLWIwOGQtNjU2ZTc2M2IzZmRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDExNTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZmI2Mjc2ZDJkZTE1Njk5NWRlMmI2OWQ0OWM4MTI4NDk3MTg4ZTVkM2ZkZDQ4OWZlNzI2NmFhMWJkNjhlOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mwkKn_MzwjK7MnlRgx3RzGtgYS3yifFEqw88HiSFWiQ)

I used your pull request, everything is fine with notifications, but the calendar in the notifications menu is still broken. 
![Screenshot from 2024-04-01 14-53-28](https://github.com/catppuccin/gtk/assets/54169870/a6f3f193-1a79-42d0-9421-8cc387e06127)

**Comment by DarioZar** [comment]
> 
> @DarioZar, I used your pull request, everything is fine with notifications, but the calendar in the notifications menu is still broken.
> 
> ![Screenshot from 2024-04-01 14-53-28](https://github.com/catppuccin/gtk/assets/54169870/a6f3f193-1a79-42d0-9421-8cc387e06127)
> 

Yes that's another issue, I made some fixes for that on my fork here https://github.com/DarioZar/Colloid-gtk-theme/commit/64ecaab3406c1f2bd64923ecd7116e89cc3b62a3

**Comment by rubyowo** [comment]
Fixed with #162, if you have further issues, please create a new issue

**Comment by IThundxr** [comment]
Seems tray icons have the same issue that the calendar has.

![image](https://github.com/catppuccin/gtk/assets/74031881/911d3595-1f9c-4ed1-a3d4-d07f8adb0290)

**Comment by fabionebbia** [comment]
Can confirm both calendar and icons are affected by this

**Comment by leafbel** [comment]
same issue

**Comment by ken-kuro** [comment]
Sorry to bring this up again, but I still have the same issue on latest version. I believe that the recent PR is missing the fix, so I updated it again https://github.com/catppuccin/gtk/pull/163

**Comment by t0msk** [comment]
Nautilus GNOME 46 is broken

![image](https://github.com/catppuccin/gtk/assets/7276200/15df3101-8f05-416b-961d-7192fbf7d2cb)

**Comment by sgoudham** [comment]
Hey :wave: 

I'm going to close this issue as I believe the initial issue has been resolved and other bugs / highlighting inconsistencies should be raised as [bug reports](https://github.com/catppuccin/gtk/issues/new?assignees=&labels=bug&projects=&template=bug.yml).
