### ISSUE TITLE
Plans for GTK2 support?

### ISSUE THREAD

**Issue by lilithium-hydride** [catppuccin/gtk#3]
Might be a stretch, especially since it isn't supported by upstream and shouldn't be used anymore anyways, but GTK2 applications such as Gpick and lxappearance (LXDE's appearance tool, useful for tweaking GTK's appearance) are themed with Colloid's fallback theme, which looks like a slightly modified version of Orchis.

**Comment by sadrach-cl** [comment]
Hi, thanks for your feedback, I don't know why but I still had problems with gtk2. But I used lxappareance and it was solved. I just generated the black versions of the theme. You should not see the other versions in white or nord. It is something I will check, could you tell me in which color variant it happens? I did my tests on Arch with i3, gnome and sway.

**Comment by lilithium-hydride** [comment]
I don't see any white or nord variants. They're dark and use an accent color that somewhat matches the color variant I selected, but still not the same. It happens with every variant on Arch with Sway, but I don't think WM would make a difference.

**Comment by sadrach-cl** [comment]
sorry, try this appearance handler ( xfce4-settings - Appearance) . it was lxapp that I had problems with.

**Comment by lilithium-hydride** [comment]
It didn't actually recognize any of my current GTK settings, which was a bit odd, but it functions properly after properly duplicating my settings for it. However, unlike lxappearance, it isn't even capable of changing the GTK2 theme, so I don't think I understand how it's supposed to help me. It's also a bit odd that it doesn't generate a .desktop file, forcing me to launch it from CLI, I don't think this was meant to be used outside of XFCE.

**Comment by sadrach-cl** [comment]
I'm working on an update, maybe 3 more days, if you want to contribute with any other detail that can help me to polish the issue, I would appreciate it very much.

**Comment by lilithium-hydride** [comment]
I'm afraid I'm not very familiar with GTK and how its themes work internally, I can only really observe what's going on from the outside. I'm happy to test things, however.

**Comment by sadrach-cl** [comment]
Thank you very much, the truth is my first work with something like this, it is a great learning, I always modify things for personal use but it is the first time I share something. It is also my first time working with git and github as well as trying to give support. I will let you know when I have something more stable for you to test it.

**Comment by lilithium-hydride** [comment]
Alright, sounds good!

**Comment by sadrach-cl** [comment]
hello, could you please test this version, greetings.
https://drive.google.com/file/d/1Rdrj9S8l2NJep7kbk82A23f69lC6F18P/view?usp=sharing
